FROM node:16-alpine

WORKDIR /app

COPY package*.json /app/
COPY .next-static /app/.next/
COPY .env.failover /app/.env
COPY next.config.js /app/
COPY node_modules /app/node_modules/

EXPOSE 3003
CMD ["npm", "run", "start-failover"]
