---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: {{appName}}
  namespace: navno
  labels:
    team: navno
  annotations:
    config.linkerd.io/proxy-cpu-limit: '2'
    config.linkerd.io/proxy-cpu-request: 500m
    config.linkerd.io/proxy-memory-limit: 2Gi
    config.linkerd.io/proxy-memory-request: 1Gi
    nais.io/run-as-user: "1001"
    nais.io/run-as-group: "1001"
spec:
  image: {{image}}
  port: 3000
  liveness:
    path: /api/internal/isAlive
    initialDelay: 20
    timeout: 10
  readiness:
    path: /api/internal/isReady
    initialDelay: 20
    timeout: 10
  prometheus:
    enabled: true
    path: /internal/metrics
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
    autoInstrumentation:
      enabled: true
      runtime: nodejs
  valkey:
    - instance: {{ valkey.instance }}
      access: readwrite
  ingresses:
    {{#each ingresses as |url|}}
    - {{url}}
    {{/each}}
  envFrom:
    - secret: {{secret}}
    - secret: nav-enonicxp-frontend-unleash-api-token
  filesFrom:
    - emptyDir:
        medium: Memory
      mountPath: /app/nextjs/.next/cache
  env:
    - name: NPM_CONFIG_CACHE
      value: /tmp/npm-cache
    - name: UNLEASH_SERVER_API_URL
      value: 'https://navno-unleash-api.nav.cloud.nais.io/api'
  strategy:
    rollingUpdate:
      maxSurge: 3
  replicas:
    disableAutoScaling: true
  accessPolicy:
    outbound:
      rules:
        - application: {{revalidatorApp}}
        - application: {{failoverApp}}
        - application: {{dekoratorenApp}}
          namespace: personbruker
      external:
        {{#each externalHosts as |host|}}
        - host: {{host}}
        {{/each}}
    inbound:
      rules:
        - application: {{revalidatorApp}}
        - application: navno-xp-archive
          namespace: personbruker
  resources:
  {{#with resources}}
    requests:
      cpu: {{requests.cpu}}
      memory: {{requests.memory}}
    limits:
      memory: {{limits.memory}}
  {{/with}}
