---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: nav-enonicxp-frontend-decorator-proxy
  namespace: personbruker
  labels:
    team: personbruker
spec:
  image: {{image}}
  team: personbruker
  port: 3001
  liveness:
    path: /api/internal/isAlive
    initialDelay: 10
    timeout: 5
  readiness:
    path: /api/internal/isReady
    initialDelay: 10
  prometheus:
    enabled: true
    path: /api/internal/metrics
  ingresses:
    - https://www.dev.nav.no
  env:
    - name: NPM_CONFIG_CACHE
      value: /tmp/npm-cache
  replicas:
    min: 2
    max: 4
  accessPolicy:
    outbound:
      rules:
        - application: nav-enonicxp-frontend-dev1