---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: {{appName}}
  namespace: personbruker
  labels:
    team: personbruker
spec:
  image: {{image}}
  team: personbruker
  port: 3000
  liveness:
    path: /api/internal/isAlive
    initialDelay: 10
    timeout: 5
  readiness:
    path: /api/internal/isReady
    initialDelay: 30
  prometheus:
    enabled: true
    path: /internal/metrics
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
  envFrom:
    - secret: {{secret}}
  replicas:
    min: 2
    max: 4
  accessPolicy:
    outbound:
      rules:
        - application: {{revalidatorApp}}
    inbound:
      rules:
        - application: {{revalidatorApp}}
  resources:
  {{#with resources}}
    limits:
      cpu: {{limits.cpu}}
      memory: {{limits.memory}}
    requests:
      cpu: {{requests.cpu}}
      memory: {{requests.memory}}
  {{/with}}