---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: nav-enonicxp-frontend
  namespace: {{namespace}}
  labels:
    team: personbruker
spec:
  image: {{image}}
  team: personbruker
  port: 3000
  liveness:
    path: /api/internal/isAlive
    initialDelay: 10
  readiness:
    path: /api/internal/isReady
    initialDelay: 10
  prometheus:
    enabled: true
    path: /api/internal/metrics
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  replicas:
    min: 2
    max: 4
  webproxy: true
  accessPolicy:
    outbound:
      external:
      {{#each outboundExternalHosts as |host|}}
         - host: {{host}}
      {{/each}}
  resources:
    limits:
      cpu: '3'
      memory: 2000Mi
    requests:
      cpu: '1'
      memory: 1500Mi
