apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: {{appName}}
  namespace: personbruker
  labels:
    team: personbruker
spec:
  image: {{image}}
  team: personbruker
  port: 3000
  liveness:
    path: /api/internal/isAlive
    initialDelay: 10
  readiness:
    path: /api/internal/isReady
    initialDelay: 10
  prometheus:
    enabled: true
    path: /internal/metrics
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  envFrom:
    - secret: {{secret}}
  env:
    - name: NPM_CONFIG_CACHE
      value: /tmp/npm-cache
  replicas:
    min: 1
    max: 2
  accessPolicy:
    inbound:
      rules:
        - application: {{frontendApp}}
    outbound:
      rules:
        - application: {{revalidatorApp}}
  resources:
    limits:
      cpu: '3'
      memory: 3000Mi
    requests:
      cpu: 500m
      memory: 1500Mi
