---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: nav-enonicxp-frontend
  namespace: {{namespace}}
  labels:
    team: personbruker
spec:
  image: {{image}}:{{version}}
  team: personbruker
  port: 3000
  liveness:
    path: /api/internal/isAlive
    initialDelay: 10
  readiness:
    path: /api/internal/isReady
    initialDelay: 10
  prometheus:
    enabled: true
    path: /_metrics
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
  vault:
    enabled: true
  replicas:
    min: 4
    max: 4
  resources:
    limits:
      cpu: '3'
      memory: 768Mi
    requests:
      memory: 512Mi
