apiVersion: nais.io/v1
kind: Naisjob
metadata:
  name: nav-enonicxp-failover-deploy-test1
  namespace: personbruker
  labels:
    team: personbruker
  annotations:
    nais.io/read-only-file-system: "false"
    nais.io/run-as-user: "0"
spec:
  securityContext:
    runAsNonRoot: false
  image: {{image}}
  team: personbruker
  envFrom:
    - secret: nav-enonicxp-dev2
    - secret: nav-enonicxp-frontend-failover
  resources:
    limits:
      cpu: '3'
      memory: 2000Mi
    requests:
      cpu: 500m
      memory: 1500Mi
