---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: {{appName}}
  namespace: navno
  labels:
    team: navno
  annotations:
    config.linkerd.io/proxy-cpu-limit: '2'
    config.linkerd.io/proxy-cpu-request: 500m
    config.linkerd.io/proxy-memory-limit: 2Gi
    config.linkerd.io/proxy-memory-request: 1Gi
spec:
  image: {{image}}
  port: 3000
  liveness:
    path: /api/internal/isAlive
    initialDelay: 5
    timeout: 10
  readiness:
    path: /api/internal/isReady
    initialDelay: 20
    timeout: 10
  prometheus:
    enabled: true
    path: /internal/metrics
  ingresses:
    {{#each ingresses as |url|}}
    - {{url}}
    {{/each}}
  envFrom:
    - secret: {{secret}}
  env:
    - name: NPM_CONFIG_CACHE
      value: /tmp/npm-cache
  replicas:
    disableAutoScaling: true
  accessPolicy:
    outbound:
      rules:
        - application: {{revalidatorApp}}
          namespace: navno
        - application: {{dekoratorenApp}}
          namespace: personbruker
      external:
        {{#each externalHosts as |host|}}
        - host: {{host}}
        {{/each}}
    inbound:
      rules:
        - application: {{frontendApp}}
  resources:
  {{#with resources}}
    requests:
      cpu: {{requests.cpu}}
      memory: {{requests.memory}}
    limits:
      memory: {{limits.memory}}
  {{/with}}