apiVersion: aiven.io/v1alpha1
kind: Redis
metadata:
  labels:
    app: nav-enonicxp-frontend
    team: personbruker
  name: redis-personbruker-{{ redis.instance }}
  namespace: personbruker
spec:
  plan: {{ redis.plan }}
  project: {{ redis.project }}
