apiVersion: aiven.io/v1alpha1
kind: Redis
metadata:
  labels:
    app: nav-enonicxp-frontend
    team: personbruker
  name: redis-personbruker-{{ redis.instance }}
  namespace: personbruker
spec:
  plan: {{ redis.plan }}
  project: {{ redis.project }}
  maintenanceWindowDow: saturday
  maintenanceWindowTime: 20:00:00
  userConfig:
    redis_maxmemory_policy: allkeys-lru

---
apiVersion: aiven.io/v1alpha1
kind: ServiceIntegration
metadata:
  labels:
    team: personbruker
  name: redis-personbruker-{{ redis.instance }}
  namespace: personbruker
spec:
  project: {{ redis.project }}
  integrationType: prometheus
  destinationEndpointId: {{ redis.endpointId }}
  sourceServiceName: redis-personbruker-{{ redis.instance }}
