name: NAIS Deploy
description: Wrapper for nais/deploy with pinned SHA

inputs:
  CLUSTER:
    required: true
    description: NAIS cluster
  RESOURCE:
    required: true
    description: Kubernetes resource file
  VAR:
    required: false
    description: Template variables (key=value pairs)
    default: ''
  VARS:
    required: false
    description: Template variables file
    default: ''

runs:
  using: composite
  steps:
    - uses: nais/deploy/actions/deploy@fa754451577294aae42872a69b888b3470478ec1 # v2
      env:
        CLUSTER: ${{ inputs.cluster }}
        RESOURCE: ${{ inputs.resource }}
        VAR: ${{ inputs.var }}
        VARS: ${{ inputs.vars }}
