apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nav-enonicxp-frontend-dev2
  namespace: personbruker
  labels:
    team: personbruker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nav-enonicxp-frontend-dev2
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
