apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nav-enonicxp-frontend-decorator-next
  namespace: personbruker
  ownerReferences:
    - apiVersion: nais.io/v1alpha1
      kind: Application
      name: nav-enonicxp-frontend-decorator-next
      uid: 4999a3c0-05f4-4c3a-be17-8f47b5c6772a
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nav-enonicxp-frontend-decorator-next
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
    - type: Pods
      pods:
        metric:
          name: http_request_duration_seconds_count
        target:
          type: AverageValue
          averageValue: '250'
