apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nav-enonicxp-frontend-dev2-failover
  namespace: personbruker
  labels:
    team: personbruker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nav-enonicxp-frontend-dev2-failover
  minReplicas: 2
  maxReplicas: 2
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Pods
          value: 2
          periodSeconds: 60
      selectPolicy: Max
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
    - type: Pods
      pods:
        metric:
          name: http_request_duration_seconds_count
        target:
          type: AverageValue
          averageValue: '250'
