apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nav-enonicxp-frontend-failover
  namespace: personbruker
  labels:
    team: personbruker
  ownerReferences:
    - apiVersion: nais.io/v1alpha1
      kind: Application
      name: nav-enonicxp-frontend-failover
      uid: ac65a21c-d6c1-4370-822e-7bb14d887b51
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nav-enonicxp-frontend-failover
  minReplicas: 2
  maxReplicas: 40
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
    - type: Pods
      pods:
        metric:
          name: http_request_duration_seconds_count
        target:
          type: AverageValue
          averageValue: '250'
