apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nav-enonicxp-frontend
  namespace: personbruker
  labels:
    team: personbruker
  ownerReferences:
    - apiVersion: nais.io/v1alpha1
      kind: Application
      name: nav-enonicxp-frontend
      uid: 475b12cf-c445-4490-ada3-fdcf73ffc510
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nav-enonicxp-frontend
  minReplicas: 2
  maxReplicas: 40
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Pods
          value: 2
          periodSeconds: 60
      selectPolicy: Max
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
    - type: Pods
      pods:
        metric:
          name: http_request_duration_seconds_count
        target:
          type: AverageValue
          averageValue: '250'
