apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: nav-enonicxp-frontend-dev2
  namespace: personbruker
  ownerReferences:
    - apiVersion: nais.io/v1alpha1
      kind: Application
      name: nav-enonicxp-frontend-dev2
      uid: d5a2e4bc-116c-4bca-adde-c16639e476b6
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nav-enonicxp-frontend-dev2
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Pods
      pods:
        metric:
          name: linkerd_request_total
        target:
          type: AverageValue
          averageValue: '500'
