apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nav-enonicxp-frontend-dev1
  namespace: personbruker
  labels:
    team: personbruker
  ownerReferences:
    - apiVersion: nais.io/v1alpha1
      kind: Application
      name: nav-enonicxp-frontend-dev1
      uid: bd92454a-03ea-4c28-9f1d-332ee70b77e6
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nav-enonicxp-frontend-dev1
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
    - type: Pods
      pods:
        metric:
          name: http_request_duration_seconds_count
        target:
          type: AverageValue
          averageValue: '250'
