const fs = require('fs').promises;
const path = require('path');

beforeAll(async () => {
    // Write a test id to the .next/BUILD_ID file. This file is
    // normally generated by Next.js during the build process and contains the commit sha as
    // the build id.
    const buildIdPath = path.join(process.cwd(), '.next');
    await fs.mkdir(buildIdPath, { recursive: true });
    await fs.writeFile(path.join(buildIdPath, 'BUILD_ID'), 'test-build-id\n', 'utf-8');
});
