export enum Owner {
    YTELSESAVDELINGEN = 'ytelsesavdelingen',
    ARBEIDS_OG_TJENESTEAVDELINGEN = 'arbeids_og_tjenesteavdelingen',
    ARBEID_OG_YTELSER_STYRINGSENHET = 'arbeid_og_ytelser_styringsenhet',
    FAMILIE_OG_PENSJONSYTELSER_STYRINGSENHET = 'familie_og_pensjonsytelser_styringsenhet',
    HR_AVDELINGEN = 'hr_avdelingen',
    JURIDISK_AVDELING = 'juridisk_avdeling',
    KUNNSKAPSAVDELINGEN = 'kunnskapsavdelingen',
    KOMMUNIKASJONSAVDELINGEN = 'kommunikasjonsavdelingen',
    OKONOMI = 'okonomi',
    STATISTIKK = 'statistikk',
    HJELPEMIDDEL_OG_TILRETTELEGGING = 'hjelpemiddel_og_tilrettelegging',
    KONTAKTSENTERET = 'kontaktsenteret',
    NAVNO = 'navno',
    IT_AVDELINGEN = 'it_avdelingen',
    FYLKE = 'fylke',
    HJELPEMIDDELSENTRALEN = 'hjelpemiddelsentralen',
    ARBEIDSLIVSSENTER = 'arbeidslivssenter',
    MIN_SIDE = 'min_side',
    DIREKTORATET = 'direktoratet',
    ANNET = 'annet',
}
