#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

current_branch=$(git rev-parse --abbrev-ref HEAD)

if [ "$current_branch" = "main" ]; then
  echo "🚫 Direct pushes to main branch are not allowed!"
  echo "Please create a pull request instead."
  exit 1
fi

npm run lint
