FROM node:16-bullseye-slim
WORKDIR /app

COPY failover /app/
COPY public /app/public/
COPY server /app/server/
COPY src /app/src/
COPY package*.json next.config.js tsconfig.json .eslintrc.json /app/

COPY deploy-linux /app/deploy

RUN apt-get install curl

RUN chmod +x /app/failover-build-and-deploy.sh
RUN chown -R 1069 /app

CMD bash -e /app/failover-build-and-deploy.sh
