name: Build docker image
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      imagename:
        required: true
        type: string
      ENV:
        required: true
        type: string
      ADMIN_ORIGIN:
        required: true
        type: string
      APP_ORIGIN:
        required: true
        type: string
      REVALIDATOR_PROXY_ORIGIN:
        required: true
        type: string
      DECORATOR_FALLBACK_URL:
        required: true
        type: string
      XP_ORIGIN:
        required: true
        type: string
      INNLOGGINGSSTATUS_URL:
        required: true
        type: string
    secrets:
      READER_TOKEN:
        required: true
    outputs:
      image:
        description: "Url to docker image"
        value: ${{ jobs.build_image.outputs.image }}

jobs:
  build_image:
    name: Build docker image
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      image: ghcr.io/${{ github.repository }}:${{ inputs.imagename }}-${{ github.sha }}
    outputs:
      image: ${{ env.image }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://npm.pkg.github.com'
          cache: 'npm'
      - name: Set app environmment
        run: |
          cat > .env <<EOF
          ENV=${{ inputs.ENV }}
          NODE_ENV=production
          ADMIN_ORIGIN=${{ inputs.ADMIN_ORIGIN }}
          APP_ORIGIN=${{ inputs.APP_ORIGIN }}
          DECORATOR_FALLBACK_URL=${{ inputs.DECORATOR_FALLBACK_URL }}
          XP_ORIGIN=${{ inputs.XP_ORIGIN }}
          REVALIDATOR_PROXY_ORIGIN=${{ inputs.REVALIDATOR_PROXY_ORIGIN }}
          INNLOGGINGSSTATUS_URL=${{ inputs.INNLOGGINGSSTATUS_URL }}
          PAGE_CACHE_DIR=/tmp/pages
          EOF
      - name: Nextjs cache
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: Build application
        run: npm run build
      - name: Login to Docker registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push docker image
        run: |
          docker build -t ${{ env.image }} .
          docker push ${{ env.image }}
