name: Deploy to dev1-failover
on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-image.yml
    permissions:
      contents: read
      id-token: write
    with:
      environment: dev-gcp:dev1
      imagename: failovr-dev1
      ENV: dev1
      NODE_ENV: production
      ADMIN_ORIGIN: https://portal-admin-dev.oera.no
      APP_ORIGIN: https://www.ansatt.dev.nav.no
      DECORATOR_URL: https://dekoratoren.ekstern.dev.nav.no
      XP_ORIGIN: https://www.dev.nav.no
      TELEMETRY_URL: https://telemetry.ekstern.dev.nav.no/collect
      REVALIDATOR_PROXY_ORIGIN: http://nav-enonicxp-frontend-revalidator-proxy-dev1
      MELDEKORT_API_URL: https://meldekort-api-q1.intern.dev.nav.no/meldekort/meldekort-api/api/person
      NAVNO_SEARCH_API_URL: https://navno-search-api.ekstern.dev.nav.no/content/search-url
      FAILOVER_ORIGIN: https://www-failover.intern.dev.nav.no
      IS_FAILOVER_INSTANCE: true
      INNLOGGINGSSTATUS_URL: https://www.ekstern.dev.nav.no/person/nav-dekoratoren-api/auth
    secrets:
      READER_TOKEN: ${{ secrets.READER_TOKEN }}
      SERVICE_SECRET: ${{ secrets.SERVICE_SECRET }}
      NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
  deploy:
    uses: ./.github/workflows/deploy-to-nais.yml
    needs: build
    permissions:
      id-token: write
    with:
      image: ${{ needs.build.outputs.image }}
      cluster: dev-gcp
      vars_file: vars-dev1-failover.yml
      config_file: config-failover.yml
      hpa_file: hpa-dev1-failover.yml
