name: Deploy pre-built image to dev
on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Url to docker image'
        required: true
        type: string
      application:
        description: 'Application instance'
        required: true
        default: 'dev1'
        type: choice
        options:
          - dev1
          - dev2
          - dev1-failover
          - dev2-failover

jobs:
  deploy:
    uses: ./.github/workflows/deploy-to-nais.yml
    with:
      image: ${{ github.event.inputs.image }}
      cluster: dev-gcp
      vars_file: vars-${{ github.event.inputs.application }}.yml
      config_file: config.yml
    secrets:
      NAIS_DEPLOY_APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
