name: Deploy-to-q6
on:
  workflow_dispatch

jobs:
  build:
    uses: ./.github/workflows/build-image.yml
    with:
      environment: dev-sbs:q6
      imagename: q6-deploy
      ENV: q6
      ADMIN_ORIGIN: https://portal-admin-q6.oera.no
      APP_ORIGIN: https://www-q6.nav.no
      DECORATOR_FALLBACK_URL: https://www-q6.nav.no/dekoratoren
      XP_ORIGIN: https://www-q6.nav.no
      INNLOGGINGSSTATUS_URL: https://innloggingsstatus.dev.nav.no/person/innloggingsstatus/auth
    secrets:
      READER_TOKEN: ${{ secrets.READER_TOKEN }}
      SERVICE_SECRET: ${{ secrets.SERVICE_SECRET }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to nais
        uses: nais/deploy/actions/deploy@v1
        env:
          CLUSTER: dev-sbs
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          RESOURCE: .nais/config.yaml
          VAR: image=${{ needs.build.outputs.image }}
          VARS: .nais/vars-q6.yaml
