name: Deploy redis
on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Instance'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

jobs:
  deploy_redis:
    name: Deploy redis instance
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Deploy to nais
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/redis.yml
          VARS: .nais/vars/vars-dev1.yml