name: workflow-test
on:
  release:
    types: [released]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod-sbs:default
    steps:
      - uses: actions/checkout@v1
      - name: Define build environment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "CI=true" >> $GITHUB_ENV
          echo "IMAGE_REGISTRY=docker.pkg.github.com/$(echo ${GITHUB_REPOSITORY})" >> $GITHUB_ENV
          echo "IMAGE_NAME=$(echo ${GITHUB_REPOSITORY##*/})" >> $GITHUB_ENV
          echo "IMAGE_VERSION=$(echo ${GITHUB_WORKFLOW})-$(echo ${GITHUB_SHA})" >> $GITHUB_ENV
          echo "GITHUB_TOKEN=$(echo ${GITHUB_TOKEN})" >> $GITHUB_ENV
      - name: Define app environmment
        env:
          SERVICE_SECRET: ${{ secrets.SERVICE_SECRET }}
        run: |
          cat > .env <<EOF
          ENV=prod
          NODE_ENV=production
          ADMIN_ORIGIN=https://portal-admin.oera.no
          APP_ORIGIN=https://www.nav.no
          DECORATOR_FALLBACK_URL=https://www.nav.no/dekoratoren
          XP_ORIGIN=https://www.nav.no
          REVALIDATOR_PROXY_ORIGIN=http://nav-enonicxp-frontend-revalidator-proxy
          SERVICE_SECRET=$SERVICE_SECRET
          EOF
      - name: Set npm version
        run: npm version ${{github.event.release.tag_name}}
