name: Deploy to prod
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod-gcp
    permissions:
      contents: read
      id-token: write
    outputs:
      image: ${{ steps.build-image.outputs.image }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Build prod image
        id: build-image
        uses: ./.github/actions/build-image
        with:
          imagename: release-${{ github.ref_name }}
          ENV: prod
          ADMIN_ORIGIN: https://portal-admin.oera.no
          APP_ORIGIN: https://www.nav.no
          REVALIDATOR_PROXY_ORIGIN: http://nav-enonicxp-frontend-revalidator-proxy
          DECORATOR_URL: https://www.nav.no/nav-dekoratoren
          XP_ORIGIN: https://www.nav.no
          TELEMETRY_URL: https://telemetry.nav.no/collect
          INNLOGGINGSSTATUS_URL: https://www.nav.no/person/nav-dekoratoren-api/auth
          NAVNO_SEARCH_API_URL: https://navno-search-api.nav.no/content/search-url
          RELEASE_TAG: ${{  github.ref_name }}
          MELDEKORT_API_URL: https://meldekort-api.nav.no/meldekort/meldekort-api/api/person
          FAILOVER_ORIGIN: https://www-failover.nav.no
          NODE_ENV: production
          nais_management_project_id: ''
          NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          READER_TOKEN: ${{ secrets.READER_TOKEN }}
          SERVICE_SECRET: ${{ secrets.SERVICE_SECRET }}

  deploy-valkey:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    needs: build
    permissions:
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Deploy Valkey
        uses: ./.github/actions/nais-deploy
        continue-on-error: true
        with:
          CLUSTER: dev-gcp
          RESOURCE: .nais/valkey.yml
          VARS: .nais/vars/dev.yml

  deploy:
    runs-on: ubuntu-latest
    needs: [build, deploy-valkey]
    permissions:
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Build and deploy prod
        uses: ./.github/actions/deploy
        with:
          image: ${{ needs.build.outputs.image }}
          cluster: prod-gcp
          vars_file: vars-prod.yml
          config_file: config.yml
          hpa_file: hpa-prod.yml
          deploy_valkey: true

  release:
    name: Create a new release
    needs: deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Generate unique tag name
        run: echo "TAG_NAME=$(date +%s)" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          target_commitish: main
          tag_name: release/prod@${{ env.TAG_NAME }} # Generates a unique tag using timestamp
          name: Release ${{ github.ref_name }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }} # This is a PAT with repo permissions
