name: Deploy to dev2
on:
  workflow_dispatch:
    inputs:
      NODE_ENV:
        description: 'Node environment'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - development

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev-gcp:dev2
    permissions:
      contents: read
      id-token: write
    outputs:
      image: ${{ steps.build-image.outputs.image }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Build dev2 image
        id: build-image
        uses: ./.github/actions/build-image
        with:
          imagename: dev2-deploy
          ENV: dev2
          ADMIN_ORIGIN: https://portal-admin-q6.oera.no
          APP_ORIGIN: https://www-2.ansatt.dev.nav.no
          REVALIDATOR_PROXY_ORIGIN: http://nav-enonicxp-frontend-revalidator-proxy-dev2
          DECORATOR_URL: https://dekoratoren-beta.intern.dev.nav.no
          XP_ORIGIN: https://www-q6.nav.no
          TELEMETRY_URL: https://telemetry.ekstern.dev.nav.no/collect
          INNLOGGINGSSTATUS_URL: https://www.ekstern.dev.nav.no/person/nav-dekoratoren-api/auth
          RELEASE_TAG: dev2-${{ github.sha }}
          MELDEKORT_API_URL: https://meldekort-api-q2.intern.dev.nav.no/meldekort/meldekort-api/api/person
          FAILOVER_ORIGIN: https://www-2-failover.intern.dev.nav.no
          NODE_ENV: ${{ inputs.NODE_ENV }}
          nais_management_project_id: ''
          NAVNO_SEARCH_API_URL: https://navno-search-api.ekstern.dev.nav.no/content/search-url
          NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          READER_TOKEN: ${{ secrets.READER_TOKEN }}
          SERVICE_SECRET: ${{ secrets.SERVICE_SECRET }}

  deploy-valkey:
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 1
    permissions:
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Deploy Valkey
        uses: nais/deploy/actions/deploy@v2
        continue-on-error: true
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/valkey.yml
          VARS: .nais/vars/dev.yml

  deploy:
    runs-on: ubuntu-latest
    needs: [build, deploy-valkey]
    permissions:
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Build and deploy dev2
        uses: ./.github/actions/deploy
        with:
          image: ${{ needs.build.outputs.image }}
          cluster: dev-gcp
          vars_file: vars-dev2.yml
          config_file: config.yml
          hpa_file: hpa-dev2.yml
          deploy_valkey: true
