name: Deploy-to-q6
on:
  workflow_dispatch

jobs:
  build:
    uses: ./.github/workflows/build-image.yml
    with:
      environment: dev-sbs:q6
      imagename: q6-deploy
      ENV: q6
      ADMIN_ORIGIN: https://portal-admin-q6.oera.no
      APP_ORIGIN: https://www-q6.nav.no
      REVALIDATOR_PROXY_ORIGIN: http://nav-enonicxp-frontend-revalidator-proxy
      DECORATOR_FALLBACK_URL: https://www-q6.nav.no/dekoratoren
      XP_ORIGIN: https://www-q6.nav.no
      INNLOGGINGSSTATUS_URL: https://innloggingsstatus.dev.nav.no/person/innloggingsstatus/auth
    secrets:
      READER_TOKEN: ${{ secrets.READER_TOKEN }}
  deploy:
    uses: ./.github/workflows/deploy-to-nais.yml
    needs: build
    with:
      image: ${{ needs.build.outputs.image }}
      cluster: dev-sbs
      vars_file: vars-q6.yml
    secrets:
      NAIS_DEPLOY_APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
