name: Deploy failover image to dev
on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Url to docker image'
        required: true
        type: string
      app_env:
        description: 'Dev environment'
        required: true
        default: 'dev1'
        type: choice
        options:
          - dev1
          - dev2

jobs:
  deploy:
    uses: ./.github/workflows/deploy-to-nais.yml
    with:
      image: ${{ github.event.inputs.image }}
      cluster: dev-gcp
      vars_file: vars-${{ github.event.inputs.app_env }}-failover.yml
      config_file: config-failover.yml
    secrets:
      NAIS_DEPLOY_APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
