name: Deploy failover image to dev
on:
  workflow_dispatch:
    inputs:
      digest:
        description: 'GAR Digest'
        required: true
        type: string
      app_env:
        description: 'Dev environment'
        required: true
        default: 'dev1'
        type: choice
        options:
          - dev1
          - dev2

jobs:
  deploy-valkey:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    permissions:
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Deploy Valkey
        uses: nais/deploy/actions/deploy@v2
        continue-on-error: true
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/valkey.yml
          VARS: .nais/vars/dev.yml

  deploy:
    runs-on: ubuntu-latest
    needs: deploy-valkey
    permissions:
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Deploy failover image to dev
        uses: ./.github/actions/deploy
        with:
          image: europe-north1-docker.pkg.dev/nais-management-233d/navno/nav-enonicxp-frontend@sha256:${{ github.event.inputs.digest }}
          cluster: dev-gcp
          vars_file: vars-${{ github.event.inputs.app_env }}-failover.yml
          config_file: config-failover.yml
