name: Deploy pre-built image to dev
on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Url to docker image'
        required: true
        type: string
      application:
        description: 'Environment'
        required: true
        default: 'dev1'
        type: choice
        options:
          - dev1
          - dev2
      failover:
        description: 'Deploy as failover'
        required: false
        type: boolean
        default: false

jobs:
  deploy:
    uses: ./.github/workflows/deploy-to-nais.yml
    with:
      image: ${{ inputs.image }}
      cluster: dev-gcp
      vars_file: vars-${{ inputs.application }}.yml
      config_file:
    secrets:
      NAIS_DEPLOY_APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
