name: Deploy-to-dev-gcp
on:
  workflow_dispatch

jobs:
  build:
    uses: ./.github/workflows/build-image.yml
    with:
      environment: dev-gcp:personbruker
      imagename: dev-gcp-deploy
      ENV: dev
      ADMIN_ORIGIN: https://portal-admin-dev.oera.no
      APP_ORIGIN: https://www.dev.nav.no
      DECORATOR_FALLBACK_URL: https://dekoratoren.ekstern.dev.nav.no
      XP_ORIGIN: https://www.dev.nav.no
      INNLOGGINGSSTATUS_URL: https://innloggingsstatus.dev.nav.no/person/innloggingsstatus/auth
    secrets:
      READER_TOKEN: ${{ secrets.READER_TOKEN }}
      SERVICE_SECRET: ${{ secrets.SERVICE_SECRET }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to nais
        uses: nais/deploy/actions/deploy@master
        env:
          CLUSTER: dev-gcp
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          RESOURCE: .nais/config.yaml
          VAR: image=${{ needs.build.outputs.image }}
          VARS: .nais/vars-dev-gcp.yaml
