name: Deploy prerendered failover to dev2
on:
  workflow_dispatch

jobs:
  build:
    uses: ./.github/workflows/build-image.yml
    with:
      environment: dev-gcp:dev2
      imagename: dev2-failover-deploy
      ENV: dev
      ADMIN_ORIGIN: https://portal-admin-q6.oera.no
      APP_ORIGIN: https://www-2.dev.nav.no
      REVALIDATOR_PROXY_ORIGIN: http://nav-enonicxp-frontend-revalidator-proxy-dev2
      DECORATOR_FALLBACK_URL: https://dekoratoren.ekstern.dev.nav.no
      XP_ORIGIN: https://www-q6.nav.no
      INNLOGGINGSSTATUS_URL: https://innloggingsstatus.dev.nav.no/person/innloggingsstatus/auth
    secrets:
      READER_TOKEN: ${{ secrets.READER_TOKEN }}
  deploy:
    uses: ./.github/workflows/deploy-to-nais.yml
    needs: build
    with:
      image: ${{ needs.build.outputs.image }}
      cluster: dev-gcp
      vars_file: vars-dev2-failover.yml
    secrets:
      NAIS_DEPLOY_APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
