name: Deploy to nais
on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      cluster:
        required: true
        type: string
      vars_file:
        required: true
        type: string
    secrets:
      NAIS_DEPLOY_APIKEY:
        required: true

jobs:
  deploy:
    name: Deploy to nais k8s (sbs)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Deploy to nais
        uses: nais/deploy/actions/deploy@v1
        env:
          CLUSTER: ${{ inputs.cluster }}
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          RESOURCE: .nais/config-sbs.yml
          VAR: image=${{ inputs.image }}
          VARS: .nais/${{ inputs.vars_file }}
