# prettier-ignore
name: Report version to Sentry
on:
  workflow_call:
    secrets:
      SENTRY_AUTH_TOKEN:
        required: true

jobs:
  report_to_sentry:
    name: Deploy to Sentry
    runs-on: ubuntu-latest
    steps:
      - name: Report release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_URL: https://sentry.gc.nav.no
          SENTRY_ORG: nav
          SENTRY_PROJECT: pb-nav-enonicxp-frontend
        with:
          environment: production
          version: ${{ github.ref_name }}
          set_commits: skip
